site_name: self-unzip.html

markdown_extensions:
  # Allows page specific configurations (like hiding certain elements, setting the title, etc)
  - meta
  # Info boxes
  - admonition
  - pymdownx.details
  # Footnotes
  - footnotes
  # Render keys
  - pymdownx.keys
  # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
      # Render diagrams
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true 
